Sunu's branch
kevagreen/saveoursons pull request #12
Opened 2021-03-17 20:15 UTC by sunu09

Branch has merge complex due to the re-design help.html.

2021-03-18 01:26 UTC, vibrio81 approved these changes
reviewed. gradle.bat red but no differences...?

2021-03-19 16:48 UTC, vibrio81 approved these changes
changes ok

2021-03-19 17:01 UTC, randyhr318 approved these changes

2021-03-19 17:58 UTC, vibrio81 commented on saveoursons/src/main/java/com/tts/saveoursons/Runner.java
> +//        crystalRepository.save(new Crystal("yello", "citrine"));
typo-missing "w" in yellow

2021-03-19 18:01 UTC, vibrio81 commented on saveoursons/src/main/resources/templates/ReportNewCase.html
> +    <div th:replace="fragments/stylesFragment :: head-styles"></div>
wrong fragment path "fragments/fragments :: head

2021-03-19 18:03 UTC, vibrio81 commented on saveoursons/src/main/resources/templates/ReportNewCase.html
> +    <div th:replace="fragments/navbar"></div>
wrong fragment path "fragments/navbar :: navbar"

2021-03-19 18:04 UTC, vibrio81 requested changes
a few code typos commented in files

2021-03-19 18:07 UTC, vibrio81 commented on saveoursons/src/main/java/com/tts/saveoursons/Runner.java
> +//        crystalRepository.save(new Crystal("yello", "citrine"));
missing w on yellow line 25

2021-03-19 20:41 UTC, closed without merging